import { Template } from "../models/Template.js";
import { Form } from "../models/Form.js";
import { User } from "../models/User.js";

export const filledFormsColumns = {
    id: Form.id,
    name: User.name,
    email: User.email,
    submittedAt: Form.submittedAt,

    singleLine1State: Template.singleLine1State,
    singleLine2State: Template.singleLine2State,
    singleLine3State: Template.singleLine3State,
    singleLine4State: Template.singleLine4State,
    multipleLine1State: Template.multipleLine1State,
    multipleLine2State: Template.multipleLine2State,
    multipleLine3State: Template.multipleLine3State,
    multipleLine4State: Template.multipleLine4State,
    integerValue1State: Template.integerValue1State,
    integerValue2State: Template.integerValue2State,
    integerValue3State: Template.integerValue3State,
    integerValue4State: Template.integerValue4State,
    checkbox1State: Template.checkbox1State,
    checkbox2State: Template.checkbox2State,
    checkbox3State: Template.checkbox3State,
    checkbox4State: Template.checkbox4State,

    singleLine1Question: Template.singleLine1Question,
    singleLine2Question: Template.singleLine2Question,
    singleLine3Question: Template.singleLine3Question,
    singleLine4Question: Template.singleLine4Question,
    multipleLine1Question: Template.multipleLine1Question,
    multipleLine2Question: Template.multipleLine2Question,
    multipleLine3Question: Template.multipleLine3Question,
    multipleLine4Question: Template.multipleLine4Question,
    integerValue1Question: Template.integerValue1Question,
    integerValue2Question: Template.integerValue2Question,
    integerValue3Question: Template.integerValue3Question,
    integerValue4Question: Template.integerValue4Question,
    checkbox1Question: Template.checkbox1Question,
    checkbox2Question: Template.checkbox2Question,
    checkbox3Question: Template.checkbox3Question,
    checkbox4Question: Template.checkbox4Question,

    singleLine1Answer: Form.singleLine1Answer,
    singleLine2Answer: Form.singleLine2Answer,
    singleLine3Answer: Form.singleLine3Answer,
    singleLine4Answer: Form.singleLine4Answer,
    multipleLine1Answer: Form.multipleLine1Answer,
    multipleLine2Answer: Form.multipleLine2Answer,
    multipleLine3Answer: Form.multipleLine3Answer,
    multipleLine4Answer: Form.multipleLine4Answer,
    integerValue1Answer: Form.integerValue1Answer,
    integerValue2Answer: Form.integerValue2Answer,
    integerValue3Answer: Form.integerValue3Answer,
    integerValue4Answer: Form.integerValue4Answer,
    checkbox1Answer: Form.checkbox1Answer,
    checkbox2Answer: Form.checkbox2Answer,
    checkbox3Answer: Form.checkbox3Answer,
    checkbox4Answer: Form.checkbox4Answer,

    singleLine1Position: Template.singleLine1Position,
    singleLine2Position: Template.singleLine2Position,
    singleLine3Position: Template.singleLine3Position,
    singleLine4Position: Template.singleLine4Position,
    multipleLine1Position: Template.multipleLine1Position,
    multipleLine2Position: Template.multipleLine2Position,
    multipleLine3Position: Template.multipleLine3Position,
    multipleLine4Position: Template.multipleLine4Position,
    integerValue1Position: Template.integerValue1Position,
    integerValue2Position: Template.integerValue2Position,
    integerValue3Position: Template.integerValue3Position,
    integerValue4Position: Template.integerValue4Position,
    checkbox1Position: Template.checkbox1Position,
    checkbox2Position: Template.checkbox2Position,
    checkbox3Position: Template.checkbox3Position,
    checkbox4Position: Template.checkbox4Position,
}